apiVersion: rds.aws.upbound.io/v1beta1
kind: DBInstance
metadata:
  name: example-db
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 20
    engine: postgres
    engineVersion: "14.1"
    instanceClass: db.t3.micro
    username: masteruser
    passwordSecretRef:
      namespace: crossplane-system
      name: rds-secret
      key: password
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    name: rds-conn
    namespace: crossplane-system
  providerConfigRef:
    name: aws-provider
