---
apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: {{ .Values.serviceName }}-ecr
spec:
  forProvider:
    region: {{ .Values.region }}
    imageScanningConfiguration:
      scanOnPush: true
    tags:
      {{- range $key, $val := .Values.tags }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  providerConfigRef:
    name: aws-provider
