---
apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  name: {{ .Values.serviceName }}-bucket
  labels:
    testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
  annotations:
    meta.upbound.io/example-id: s3/v1beta2/bucket
spec:
  forProvider:
    bucket: {{ .Values.serviceName }}-bucket
    region: {{ .Values.region }}
    objectLockEnabled: true
    tags:
      {{- range $key, $val := .Values.tags }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  providerConfigRef:
    name: aws-provider
---
apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketACL
metadata:
  name: {{ .Values.serviceName }}-bucket-acl
spec:
  forProvider:
    acl: private
    region: {{ .Values.region }}
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
  providerConfigRef:
    name: aws-provider
---
apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketLogging
metadata:
  name: {{ .Values.serviceName }}-bucket-logging
  labels:
    testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
spec:
  forProvider:
    region: {{ .Values.region }}
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
    targetBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
    targetPrefix: log/
  providerConfigRef:
    name: aws-provider
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPublicAccessBlock
metadata:
  name: {{ .Values.serviceName }}-bucket-public-access
  labels:
    testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
spec:
  forProvider:
    region: {{ .Values.region }}
    blockPublicAcls: false
    blockPublicPolicy: false
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: {{ .Values.serviceName }}-bucket
  providerConfigRef:
    name: aws-provider
